name: Portfolio Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy static site to S3 bucket
        run: |
          aws s3 sync . s3://tws-portfolio-12345 \
            --delete \
            --exact-timestamps \
            --cache-control "no-cache" \
            --content-type "text/html" --exclude "*" --include "*.html"
          aws s3 sync . s3://tws-portfolio-12345 \
            --exact-timestamps \
            --cache-control "no-cache" \
            --content-type "text/css" --exclude "*" --include "*.css"
          aws s3 sync . s3://tws-portfolio-12345 \
            --exact-timestamps \
            --cache-control "no-cache" \
            --content-type "application/javascript" --exclude "*" --include "*.js"
          aws s3 sync . s3://tws-portfolio-12345 \
            --exact-timestamps \
            --cache-control "no-cache" \
            --exclude "*.html" --exclude "*.css" --exclude "*.js"
